apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "netctl.fullname" . }}-config
  labels:
    {{- include "netctl.labels" . | nindent 4 }}
data:
  NETCTL_HTTP_ADDR: ":8080"
  NETCTL_HSTS_ENABLED: "true"
  NETCTL_LOG_FORMAT: {{ .Values.control.logFormat | quote }}
  NETCTL_LOG_LEVEL: {{ .Values.control.logLevel | quote }}
  NETCTL_AUTH_MODE: {{ .Values.control.authMode | quote }}
  NETCTL_SECURITY_CONTACT: {{ .Values.control.securityContact | quote }}
  {{- if .Values.oidc.issuer }}
  NETCTL_OIDC_ISSUER: {{ .Values.oidc.issuer | quote }}
  NETCTL_OIDC_CLIENT_ID: {{ .Values.oidc.clientId | quote }}
  NETCTL_OIDC_REDIRECT_URL: {{ .Values.oidc.redirectUrl | quote }}
  {{- end }}
  {{- range $k, $v := .Values.control.extraEnv }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
