// SPDX-License-Identifier: LicenseRef-probectl-TBD

// Command gendigests writes internal/ebpf/bpf_digests_ebpf.go: the SHA-256
// manifest of the bpf2go-compiled BPF objects (U-014). It runs inside `make
// ebpf-agent`, right after bpf2go and before `go build -tags ebpf`, so the
// digests baked into the agent describe exactly the objects baked into the
// agent — the loaders verify the embedded bytes against this manifest before
// any kernel load.
package main

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/imfeelingtheagi/probectl/internal/ebpf"
)

func main() {
	dir := "."
	if len(os.Args) > 1 {
		dir = os.Args[1]
	}
	matches, err := filepath.Glob(filepath.Join(dir, "*_bpfel.o"))
	if err != nil || len(matches) == 0 {
		fmt.Fprintln(os.Stderr, "gendigests: no *_bpfel.o objects found (run bpf2go first)")
		os.Exit(1)
	}
	sort.Strings(matches)

	var b strings.Builder
	b.WriteString(`//go:build ebpf

// Code generated by internal/ebpf/gendigests (make ebpf-agent); DO NOT EDIT.
// SHA-256 manifest of the embedded BPF objects, verified before kernel load
// (U-014).

package ebpf

var bpfObjectDigests = map[string]string{
`)
	for _, m := range matches {
		raw, err := os.ReadFile(m)
		if err != nil {
			fmt.Fprintf(os.Stderr, "gendigests: read %s: %v\n", m, err)
			os.Exit(1)
		}
		name := strings.TrimSuffix(filepath.Base(m), "_bpfel.o")
		fmt.Fprintf(&b, "\t%q: %q,\n", name, ebpf.ObjectDigest(raw))
	}
	b.WriteString("}\n")

	out := filepath.Join(dir, "bpf_digests_ebpf.go")
	if err := os.WriteFile(out, []byte(b.String()), 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "gendigests: write %s: %v\n", out, err)
		os.Exit(1)
	}
	fmt.Printf("gendigests: wrote %s (%d objects)\n", out, len(matches))
}
