#!/usr/bin/env bash
# Regenerate the third-party Go dependency license
# inventory + NOTICE from the module graph. Dependency-free — `go list` plus a
# scan of each module's cached LICENSE/COPYING file (no external tool to pin per
# the supply-pins policy). The detected license is a keyword HEURISTIC; it must
# be verified before any commercial/MSP resale (the code-dependency counterpart
# of docs/opendata-aup.md). Re-run after go.mod changes; commit both outputs.
set -euo pipefail
cd "$(dirname "$0")/.."
export GOWORK=off

NOTICE_FILE="NOTICE"
INV_FILE="docs/third-party-licenses.md"
mainmod="$(go list -m)"

detect_license() { # detect_license <module-dir>
  local dir="$1" f head
  [ -n "$dir" ] || { echo "UNKNOWN (module dir unavailable)"; return; }
  f="$(ls "$dir"/LICENSE* "$dir"/COPYING* "$dir"/License* 2>/dev/null | head -1 || true)"
  [ -n "$f" ] || { echo "UNKNOWN (no LICENSE file)"; return; }
  head="$(head -40 "$f" 2>/dev/null || true)"
  case "$head" in
    *"Apache License"*"Version 2.0"*) echo "Apache-2.0" ;;
    *"Permission is hereby granted, free of charge"*) echo "MIT" ;;
    *"Mozilla Public License"*"2.0"*) echo "MPL-2.0" ;;
    *"GNU LESSER GENERAL PUBLIC"*) echo "LGPL" ;;
    *"GNU GENERAL PUBLIC"*) echo "GPL" ;;
    *"ISC License"*|*"ISC license"*) echo "ISC" ;;
    *"Redistribution and use in source and binary forms"*) echo "BSD" ;;
    *) echo "see module ($(basename "$f"))" ;;
  esac
}

mods="$(go list -deps -f '{{with .Module}}{{.Path}}|{{.Version}}|{{.Dir}}{{end}}' ./... 2>/dev/null | sort -u)"

{
  echo "probectl — THIRD-PARTY NOTICES"
  echo
  echo "probectl is built with the third-party Go modules listed below, each under"
  echo "its own license. GENERATED by scripts/gen_third_party.sh from the module"
  echo "graph — do not hand-edit. Full license texts ship in each module (the Go"
  echo "module cache / a vendor tree); the per-module inventory with detected"
  echo "licenses is docs/third-party-licenses.md."
  echo
} >"$NOTICE_FILE"

{
  echo "# Third-party Go dependencies"
  echo
  echo "Generated by \`scripts/gen_third_party.sh\` from \`go list -deps ./...\` (the"
  echo "modules compiled into the shipped binaries). The License column is a"
  echo "keyword HEURISTIC over each module's cached LICENSE file — **verify before"
  echo "commercial/MSP resale** (the code-dependency counterpart of the"
  echo "provenance duty in \`docs/opendata-aup.md\`)."
  echo
  echo "| Module | Version | License (detected) |"
  echo "|---|---|---|"
} >"$INV_FILE"

n=0
while IFS='|' read -r path ver dir; do
  [ -n "${path:-}" ] || continue
  [ "$path" = "$mainmod" ] && continue
  [ -n "${ver:-}" ] || continue # the main module / a local replace has no version
  lic="$(detect_license "${dir:-}")"
  printf '| `%s` | %s | %s |\n' "$path" "$ver" "$lic" >>"$INV_FILE"
  printf -- '- %s %s — %s\n' "$path" "$ver" "$lic" >>"$NOTICE_FILE"
  n=$((n + 1))
done <<<"$mods"

echo "gen_third_party: wrote $NOTICE_FILE + $INV_FILE ($n modules)."
