#!/usr/bin/env bash
#
# release_notes.sh [FROM] [TO] — conventional-commit-grouped release notes
# (U-087). FROM defaults to the latest tag, TO to HEAD. Used to prepend the
# CHANGELOG.md section at each release; the GitHub release body itself is
# auto-generated (release.yml: generate_release_notes), so this keeps the
# in-repo history equally automated.
#
#   scripts/release_notes.sh v0.3.0 v0.4.0
#   scripts/release_notes.sh                # latest tag → HEAD (the next section)
set -euo pipefail

FROM="${1:-$(git describe --tags --abbrev=0)}"
TO="${2:-HEAD}"

section() { # <title> <regex over the conventional type>
  local body
  body="$(git log --no-merges --pretty='- %s' "${FROM}..${TO}" | grep -E "^- ($2)(\(|: |!)" || true)"
  [ -n "$body" ] || return 0
  echo "### $1"
  echo
  echo "$body"
  echo
}

echo "<!-- generated by scripts/release_notes.sh ${FROM}..${TO} -->"
section "Features"        "feat"
section "Fixes"           "fix"
section "Performance"     "perf"
section "Security & CI"   "ci|build"
section "Tests"           "test"
section "Documentation"   "docs"
section "Maintenance"     "chore|style|refactor"
